### ISSUE TITLE
Call stack exceeded error due to change in PouchDB clone()

### ISSUE THREAD

**Issue by nolanlawson** [pouchdb/pouchdb-security#2]
PouchDB's `clone()` has changed, so we can no longer pass recursive or non-JSON objects into the PouchDB constructor.

[This line](https://github.com/pouchdb/pouchdb-security/blob/7beecd428840cd896a973d437b5a338f277e83bd/index.js#L206) causes an endless error.

You can repro in the local-npm project by checking out a branch where I ran into this issue:

```
hub clone nolanlawson/local-npm
cd local-npm
git checkout update-pouchdb-5
./bin.js
```

**Comment by marten-de-vries** [comment]
I really need to get the tests ported to JS for these projects, I hate not being able to run the tests while these projects formerly had 100% coverage. Anyway, this is too important, and the solution is fine.

:+1:

**Comment by nolanlawson** [comment]
ca43145aeeb268225b3638853fa264a17c18c388
